services:
  peliculas:
    build: .
    container_name: peliculas-app
    ports:
      - "1080:1080"
    volumes:
      - data:/app
    working_dir: /app
    command: ["./peliculas"]
    stdin_open: true
    tty: true
    restart: always

volumes:
  data:
